const trailsData = [
    {
        "trail_name": "Ainsworth Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 0.5,
        "high_point(feet)": 150,
        "elevation_gain(feet)": 85,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.56058,
        "longitude": -122.17239
    },
    {
        "trail_name": "Aldrich Butte Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 13.8,
        "high_point(feet)": 1140,
        "elevation_gain(feet)": 2405,
        "difficulty": "Moderate",
        "seasons": "All Season",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.5209,
        "longitude": -121.56
    },
    {
        "trail_name": "Aldrich Butte-Cedar Falls Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 16.4,
        "high_point(feet)": 1140,
        "elevation_gain(feet)": 3105,
        "difficulty": "Difficult",
        "seasons": "Year round",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.40803,
        "longitude": -121.87142
    },
    {
        "trail_name": "Angels Rest Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.8,
        "high_point(feet)": 1640,
        "elevation_gain(feet)": 1475,
        "difficulty": "Moderate",
        "seasons": "All Season",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.56034,
        "longitude": -122.1726
    },
    {
        "trail_name": "Angels Rest-Devils Rest Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 10.8,
        "high_point(feet)": 2435,
        "elevation_gain(feet)": 3040,
        "difficulty": "Moderate",
        "seasons": "All Season",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.56053,
        "longitude": -122.17251
    },
    {
        "trail_name": "Archer Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 6.3,
        "high_point(feet)": 2020,
        "elevation_gain(feet)": 1780,
        "difficulty": "Moderate",
        "seasons": "Spring through fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.5777,
        "longitude": -122.11719
    },
    {
        "trail_name": "Augspurger Mountain Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 12.6,
        "high_point(feet)": 3667,
        "elevation_gain(feet)": 4767,
        "difficulty": "Difficult",
        "seasons": "Spring through fall; snowshoe in winter",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 43.73795,
        "longitude": -122.42298
    },
    {
        "trail_name": "Balfour-Klickitat Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 0.7,
        "high_point(feet)": 220,
        "elevation_gain(feet)": 115,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.85,
        "longitude": -121.15
    },
    {
        "trail_name": "Beacon Rock Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.8,
        "high_point(feet)": 848,
        "elevation_gain(feet)": 680,
        "difficulty": "Moderate",
        "seasons": "\"Year round",
        "family_friendly": "except during ice storms\"",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 43.10526
    },
    {
        "trail_name": "Bear Lake Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.6,
        "high_point(feet)": 4100,
        "elevation_gain(feet)": 480,
        "difficulty": "Easy",
        "seasons": "Summer/Fall",
        "family_friendly": "Yes",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.74286,
        "longitude": -121.88889
    },
    {
        "trail_name": "Bell Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 17,
        "high_point(feet)": 3195,
        "elevation_gain(feet)": 3330,
        "difficulty": "Difficult",
        "seasons": "May-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Crowded to Triple Falls",
        "latitude": 45.58861,
        "longitude": -122.07832
    },
    {
        "trail_name": "Benson Plateau Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 16.4,
        "high_point(feet)": 4095,
        "elevation_gain(feet)": 4030,
        "difficulty": "Difficult",
        "seasons": "Late May into October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Yes",
        "latitude": 45.645,
        "longitude": -121.91828
    },
    {
        "trail_name": "Bridal Veil Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.4,
        "high_point(feet)": 230,
        "elevation_gain(feet)": 205,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.5536,
        "longitude": -122.1824
    },
    {
        "trail_name": "Buck Creek on Larch Mountain Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.8,
        "high_point(feet)": 1680,
        "elevation_gain(feet)": 310,
        "difficulty": "Easy",
        "seasons": "\"All year",
        "family_friendly": "except during winter snows\"",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": "No",
        "longitude": 45.5777
    },
    {
        "trail_name": "Buck Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.8,
        "high_point(feet)": 710,
        "elevation_gain(feet)": 600,
        "difficulty": "Easy",
        "seasons": "Year-round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.86396,
        "longitude": -122.64244
    },
    {
        "trail_name": "Camp Benson Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.9,
        "high_point(feet)": 460,
        "elevation_gain(feet)": 430,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.42771,
        "longitude": -122.81956
    },
    {
        "trail_name": "Cape Horn Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.4,
        "high_point(feet)": 1300,
        "elevation_gain(feet)": 1230,
        "difficulty": "Moderate",
        "seasons": "July 16th to January 31st for the loop",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.76297,
        "longitude": -123.95604
    },
    {
        "trail_name": "Cape Horn Overlooks Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 8.6,
        "high_point(feet)": 1300,
        "elevation_gain(feet)": 1795,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 42.83294,
        "longitude": -124.54789
    },
    {
        "trail_name": "Cascade Locks West Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3,
        "high_point(feet)": 280,
        "elevation_gain(feet)": 100,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.04197,
        "longitude": -123.9923
    },
    {
        "trail_name": "Casey Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11.3,
        "high_point(feet)": 4035,
        "elevation_gain(feet)": 3995,
        "difficulty": "Difficult",
        "seasons": "Summer into Fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 43.9036,
        "longitude": -123.56705
    },
    {
        "trail_name": "Catherine Creek Arch Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.4,
        "high_point(feet)": 615,
        "elevation_gain(feet)": 500,
        "difficulty": "Easy",
        "seasons": "\"Year round",
        "family_friendly": "best Mar-May\"",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 43.07258
    },
    {
        "trail_name": "Catherine Creek Canyon Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 5.8,
        "high_point(feet)": 1425,
        "elevation_gain(feet)": 1390,
        "difficulty": "Moderate",
        "seasons": "\"All year",
        "family_friendly": "best March through May\"",
        "backpackable": "For older kids",
        "crowded": "No",
        "latitude": "Only in lower areas",
        "longitude": 42.86542
    },
    {
        "trail_name": "Catherine Creek Universal Access Hike",
        "trail_type": "loop",
        "distance(miles)": 1.2,
        "high_point(feet)": 265,
        "elevation_gain(feet)": 90,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Catherine Creek West Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.4,
        "high_point(feet)": 1310,
        "elevation_gain(feet)": 1040,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 44.10079,
        "longitude": -121.62241
    },
    {
        "trail_name": "Catherine Creek-Coyote Wall Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11,
        "high_point(feet)": 1615,
        "elevation_gain(feet)": 2640,
        "difficulty": "Moderate",
        "seasons": "\"Year round",
        "family_friendly": "best March–May\"",
        "backpackable": "No",
        "crowded": "No",
        "latitude": "\"Yes",
        "longitude": "on spring weekends\""
    },
    {
        "trail_name": "Catherine Creek-Rowland Basin Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 4.9,
        "high_point(feet)": 1300,
        "elevation_gain(feet)": 1320,
        "difficulty": "Moderate",
        "seasons": "All year: best time is spring",
        "family_friendly": "\"Yes",
        "backpackable": "for older children\"",
        "crowded": "No",
        "latitude": "On Sunflower Hill",
        "longitude": 44.10079
    },
    {
        "trail_name": "Cedar Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 17.1,
        "high_point(feet)": 1995,
        "elevation_gain(feet)": 3970,
        "difficulty": "Difficult",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "o",
        "crowded": "No",
        "latitude": 45.45202,
        "longitude": -122.87016
    },
    {
        "trail_name": "Chenoweth Tableland Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.5,
        "high_point(feet)": 775,
        "elevation_gain(feet)": 620,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Chinidere Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 4.4,
        "high_point(feet)": 4673,
        "elevation_gain(feet)": 1140,
        "difficulty": "Moderate",
        "seasons": "Early Summer through Fall",
        "family_friendly": "Yes",
        "backpackable": "\"Yes - connects to Gorge trail network",
        "crowded": "camping at \"",
        "latitude": "Peak summer weekends",
        "longitude": 45.68272
    },
    {
        "trail_name": "Columbia Gorge Traverse Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 34.7,
        "high_point(feet)": 1855,
        "elevation_gain(feet)": 4725,
        "difficulty": "Moderate (in sections)",
        "seasons": "All year",
        "family_friendly": "\"Yes",
        "backpackable": "in short sections\"",
        "crowded": "Yes",
        "latitude": "No",
        "longitude": 45.7253
    },
    {
        "trail_name": "Cook Hill Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 8.8,
        "high_point(feet)": 3015,
        "elevation_gain(feet)": 2930,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.42878,
        "longitude": -121.92284
    },
    {
        "trail_name": "Cougar Rock via Elevator Shaft Hike",
        "trail_type": "loop",
        "distance(miles)": 6.7,
        "high_point(feet)": 1850,
        "elevation_gain(feet)": 1860,
        "difficulty": "Difficult",
        "seasons": "Apr-Oct",
        "family_friendly": "No. Stony scramble & poison oak",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Coyote Wall Hike",
        "trail_type": "loop",
        "distance(miles)": 7.8,
        "high_point(feet)": 1895,
        "elevation_gain(feet)": 1775,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "\"Yes",
        "backpackable": "but take care at the cliffs\"",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 45.2974
    },
    {
        "trail_name": "Dalles Mountain Ranch Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 6.9,
        "high_point(feet)": 1310,
        "elevation_gain(feet)": 1060,
        "difficulty": "Moderate",
        "seasons": "Year-round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 44.06101,
        "longitude": -122.06181
    },
    {
        "trail_name": "Devils Hole/Three Benches Hike",
        "trail_type": "loop",
        "distance(miles)": 2.7,
        "high_point(feet)": 670,
        "elevation_gain(feet)": 800,
        "difficulty": "Moderate",
        "seasons": "Year round: Spring is best",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Devils Rest via Wahkeena Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 8.4,
        "high_point(feet)": 2435,
        "elevation_gain(feet)": 2350,
        "difficulty": "Moderate",
        "seasons": "Year round (periods of snow during winter)",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "\"Initially yes",
        "latitude": "but quieter as you go higher\"",
        "longitude": 45.5774
    },
    {
        "trail_name": "Dog Mountain Hike",
        "trail_type": "loop",
        "distance(miles)": 6.9,
        "high_point(feet)": 2948,
        "elevation_gain(feet)": 2800,
        "difficulty": "Moderate",
        "seasons": "\"All year",
        "family_friendly": "except during exceptional snowfall\"",
        "backpackable": "No",
        "crowded": "No",
        "latitude": "\"Yes",
        "longitude": "in spring and summer\""
    },
    {
        "trail_name": "Dog Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.4,
        "high_point(feet)": 2948,
        "elevation_gain(feet)": 2800,
        "difficulty": "Moderate",
        "seasons": "\"Year round",
        "family_friendly": "except during winter storms\"",
        "backpackable": "No",
        "crowded": "No",
        "latitude": "\"Yes",
        "longitude": "especially in spring and summer\""
    },
    {
        "trail_name": "Dublin Lake Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 13.8,
        "high_point(feet)": 3760,
        "elevation_gain(feet)": 3780,
        "difficulty": "Difficult",
        "seasons": "Apr-Nov",
        "family_friendly": "Too long",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.17697,
        "longitude": -121.91399
    },
    {
        "trail_name": "Duncan Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.3,
        "high_point(feet)": 2050,
        "elevation_gain(feet)": 1100,
        "difficulty": "Moderate",
        "seasons": "Spring through fall",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "No",
        "longitude": 42.91206
    },
    {
        "trail_name": "Eagle Creek Overlook Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.6,
        "high_point(feet)": 170,
        "elevation_gain(feet)": 175,
        "difficulty": "Easy",
        "seasons": "October 1st to May 30th",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.63674,
        "longitude": -121.91974
    },
    {
        "trail_name": "Eagle Creek to High Bridge Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6.4,
        "high_point(feet)": 640,
        "elevation_gain(feet)": 840,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "\"No",
        "backpackable": "not suitable for young children because of the narrow passage",
        "crowded": "in places",
        "latitude": "along very high cliffs.\"",
        "longitude": "No"
    },
    {
        "trail_name": "Eagle Creek to Punch Bowl Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.2,
        "high_point(feet)": 505,
        "elevation_gain(feet)": 525,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 45.64045
    },
    {
        "trail_name": "Eagle Creek to Tunnel Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 12,
        "high_point(feet)": 1080,
        "elevation_gain(feet)": 1640,
        "difficulty": "Difficult",
        "seasons": "Year round",
        "family_friendly": "\"No",
        "backpackable": "the trail is steep",
        "crowded": "uneven",
        "latitude": "and rocky",
        "longitude": "with narrow sections and cliff paths. Some say it's not ideal for children or dogs. \""
    },
    {
        "trail_name": "Eagle-Benson Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 15.8,
        "high_point(feet)": 4110,
        "elevation_gain(feet)": 4260,
        "difficulty": "Difficult",
        "seasons": "June-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Yes (on Eagle Creek Trail)",
        "latitude": 43.83987,
        "longitude": -122.71252
    },
    {
        "trail_name": "EasyCLIMB Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.8,
        "high_point(feet)": 180,
        "elevation_gain(feet)": 170,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Elowah Falls Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.1,
        "high_point(feet)": 255,
        "elevation_gain(feet)": 340,
        "difficulty": "Easy",
        "seasons": "Year-round except during winter storms",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "\"Yes",
        "latitude": "as far as the falls\"",
        "longitude": 45.61248
    },
    {
        "trail_name": "Fairy Falls Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.4,
        "high_point(feet)": 1575,
        "elevation_gain(feet)": 1495,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Fort Cascades Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1.3,
        "high_point(feet)": 60,
        "elevation_gain(feet)": 15,
        "difficulty": "Easy",
        "seasons": "year-round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 46.22677,
        "longitude": -124.01276
    },
    {
        "trail_name": "Fort Rains Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.8,
        "high_point(feet)": 175,
        "elevation_gain(feet)": 80,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 46.13407,
        "longitude": -123.88057
    },
    {
        "trail_name": "Franklin Ridge from Larch Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11.8,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 2460,
        "difficulty": "Difficult",
        "seasons": "Summer - mid-fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "\"No",
        "latitude": "except at Sherrard Point\"",
        "longitude": 45.5777
    },
    {
        "trail_name": "Franklin Ridge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11.1,
        "high_point(feet)": 2930,
        "elevation_gain(feet)": 3205,
        "difficulty": "Difficult",
        "seasons": "Mid-spring - fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Not above the Wahkeena Trail junction",
        "latitude": 45.5209,
        "longitude": -121.56
    },
    {
        "trail_name": "Gillette Lake Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 5.6,
        "high_point(feet)": 435,
        "elevation_gain(feet)": 650,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 42.07125,
        "longitude": -123.29864
    },
    {
        "trail_name": "Green Point Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 8,
        "high_point(feet)": 4737,
        "elevation_gain(feet)": 1275,
        "difficulty": "Moderate",
        "seasons": "Summer into Fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.39804,
        "longitude": -120.70932
    },
    {
        "trail_name": "Hamilton Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.3,
        "high_point(feet)": 75,
        "elevation_gain(feet)": 20,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 42.45647,
        "longitude": -123.5222
    },
    {
        "trail_name": "Hamilton Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.5,
        "high_point(feet)": 2438,
        "elevation_gain(feet)": 2100,
        "difficulty": "Moderate",
        "seasons": "March to November",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.41797,
        "longitude": -122.69155
    },
    {
        "trail_name": "Hamilton-Hardy Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 13,
        "high_point(feet)": 2957,
        "elevation_gain(feet)": 3505,
        "difficulty": "Difficult",
        "seasons": "Spring through fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "On Hamilton Mountain",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Hardy Ridge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 8.1,
        "high_point(feet)": 2957,
        "elevation_gain(feet)": 2175,
        "difficulty": "Moderate",
        "seasons": "Spring through fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.64122,
        "longitude": -122.03234
    },
    {
        "trail_name": "Herman Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 15.4,
        "high_point(feet)": 2925,
        "elevation_gain(feet)": 2970,
        "difficulty": "Difficult",
        "seasons": "All year",
        "family_friendly": "\"Yes",
        "backpackable": "for a shorter distance\"",
        "crowded": "Yes",
        "latitude": "On summer weekends",
        "longitude": 45.68295
    },
    {
        "trail_name": "Herman Creek Pinnacles Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.6,
        "high_point(feet)": 970,
        "elevation_gain(feet)": 1305,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "\"Yes",
        "latitude": "on weekends\"",
        "longitude": 45.68295
    },
    {
        "trail_name": "Herman Creek Pinnacles via the PCT Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 7.4,
        "high_point(feet)": 950,
        "elevation_gain(feet)": 1610,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "On the first section to Dry Creek Falls",
        "latitude": 45.68295,
        "longitude": -121.84194
    },
    {
        "trail_name": "Herman Creek-Wyeth Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 10.8,
        "high_point(feet)": 960,
        "elevation_gain(feet)": 2175,
        "difficulty": "Moderate",
        "seasons": "Year-Round",
        "family_friendly": "Yes (as a car shuttle)",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.68295,
        "longitude": -121.84194
    },
    {
        "trail_name": "Hood River Pipeline Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.3,
        "high_point(feet)": 200,
        "elevation_gain(feet)": 110,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "On summer weekends",
        "latitude": 45.38337,
        "longitude": -122.7408
    },
    {
        "trail_name": "Hood River Waterfront Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6.4,
        "high_point(feet)": 95,
        "elevation_gain(feet)": 15,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.38337,
        "longitude": -122.7408
    },
    {
        "trail_name": "Horsetail Falls Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.6,
        "high_point(feet)": 395,
        "elevation_gain(feet)": 565,
        "difficulty": "Easy",
        "seasons": "\"All year",
        "family_friendly": "except during winter storms\"",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 45.59038
    },
    {
        "trail_name": "Horsethief Butte Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.7,
        "high_point(feet)": 498,
        "elevation_gain(feet)": 250,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Only on easier trails",
        "backpackable": "No",
        "crowded": "\"Yes",
        "latitude": "on spring weekends\"",
        "longitude": 43.97423
    },
    {
        "trail_name": "Indian Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.2,
        "high_point(feet)": 480,
        "elevation_gain(feet)": 250,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.70533,
        "longitude": -121.50809
    },
    {
        "trail_name": "Indian Mountain Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11.5,
        "high_point(feet)": 4865,
        "elevation_gain(feet)": 2640,
        "difficulty": "Moderate",
        "seasons": "Summer into Fall",
        "family_friendly": "No",
        "backpackable": "es",
        "crowded": "No",
        "latitude": 45.41797,
        "longitude": -122.69155
    },
    {
        "trail_name": "Indian Point Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.8,
        "high_point(feet)": 2935,
        "elevation_gain(feet)": 2730,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "On summer weekends",
        "latitude": 45.93084,
        "longitude": -123.97859
    },
    {
        "trail_name": "Klickitat Canyon Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6.8,
        "high_point(feet)": 645,
        "elevation_gain(feet)": 100,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 42.61653,
        "longitude": -120.60622
    },
    {
        "trail_name": "Klickitat Trail: Klickitat Mineral Springs Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 5.2,
        "high_point(feet)": 545,
        "elevation_gain(feet)": 50,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.85,
        "longitude": -121.15
    },
    {
        "trail_name": "Klickitat Trail: Lyle to Klickitat Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 13,
        "high_point(feet)": 465,
        "elevation_gain(feet)": 340,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.85,
        "longitude": -121.15
    },
    {
        "trail_name": "Klickitat Trail: Swale Canyon Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 15,
        "high_point(feet)": 1560,
        "elevation_gain(feet)": 1010,
        "difficulty": "Moderate",
        "seasons": "Fall through spring (closed in summer)",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.33765,
        "longitude": -121.91561
    },
    {
        "trail_name": "Labyrinth Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.6,
        "high_point(feet)": 1005,
        "elevation_gain(feet)": 915,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Labyrinth-Coyote Wall Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.3,
        "high_point(feet)": 1655,
        "elevation_gain(feet)": 1790,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 45.7253
    },
    {
        "trail_name": "Larch Mountain Crater Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 6.3,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 1310,
        "difficulty": "Moderate",
        "seasons": "May - November",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.52932,
        "longitude": -122.08834
    },
    {
        "trail_name": "Larch Mountain Crater Rim Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 6.2,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 1440,
        "difficulty": "Moderate",
        "seasons": "Summer - mid-fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "\"No",
        "latitude": "except at Sherrard Point\"",
        "longitude": 45.5777
    },
    {
        "trail_name": "Larch Mountain Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 14.4,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 4010,
        "difficulty": "Difficult",
        "seasons": "Apr–Nov",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Extremely crowded to the upper viewpoint; quite cr",
        "latitude": 45.5777,
        "longitude": -122.11719
    },
    {
        "trail_name": "Larch Mountain via Oneonta Trail Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 17.2,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 4400,
        "difficulty": "Difficult",
        "seasons": "May - October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "As far as Triple Falls",
        "latitude": 45.5777,
        "longitude": -122.11719
    },
    {
        "trail_name": "Latourell Falls Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.4,
        "high_point(feet)": 620,
        "elevation_gain(feet)": 625,
        "difficulty": "Easy",
        "seasons": "Year round except during winter storms",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.53859,
        "longitude": -122.21808
    },
    {
        "trail_name": "Leidl Ridge Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 9.1,
        "high_point(feet)": 2140,
        "elevation_gain(feet)": 1115,
        "difficulty": "Moderate",
        "seasons": "Spring through fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.49081,
        "longitude": -122.29634
    },
    {
        "trail_name": "Lewis and Clark Park Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3,
        "high_point(feet)": 160,
        "elevation_gain(feet)": 100,
        "difficulty": "Easy",
        "seasons": "Year-Round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Sometimes",
        "latitude": 45.42056,
        "longitude": -122.55284
    },
    {
        "trail_name": "Little Beacon Rock Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1.6,
        "high_point(feet)": 730,
        "elevation_gain(feet)": 375,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 43.35647,
        "longitude": -122.72018
    },
    {
        "trail_name": "Lower Starvation Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.1,
        "high_point(feet)": 790,
        "elevation_gain(feet)": 795,
        "difficulty": "Moderate",
        "seasons": "Year Round",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.68839,
        "longitude": -121.68993
    },
    {
        "trail_name": "Lyle Cherry Orchard Hike",
        "trail_type": "loop",
        "distance(miles)": 6.5,
        "high_point(feet)": 1245,
        "elevation_gain(feet)": 1340,
        "difficulty": "Moderate",
        "seasons": "\"All year",
        "family_friendly": "best in spring and fall\"",
        "backpackable": "\"Yes",
        "crowded": "for older kids\"",
        "latitude": "No",
        "longitude": "On spring weekends"
    },
    {
        "trail_name": "Maryhill Loops Hike",
        "trail_type": "loop",
        "distance(miles)": 5.9,
        "high_point(feet)": 1560,
        "elevation_gain(feet)": 820,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.49936,
        "longitude": -122.69368
    },
    {
        "trail_name": "McCall Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.4,
        "high_point(feet)": 1722,
        "elevation_gain(feet)": 1070,
        "difficulty": "Moderate",
        "seasons": "March 1st to October 31st (closed in the wet season to prevent erosion)",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "Yes",
        "longitude": 45.68272
    },
    {
        "trail_name": "McCord Creek to Tanner Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 7.1,
        "high_point(feet)": 335,
        "elevation_gain(feet)": 820,
        "difficulty": "Moderate",
        "seasons": "Year-round except during winter storms",
        "family_friendly": "Only short distances",
        "backpackable": "No",
        "crowded": "Only as far as Elowah Falls",
        "latitude": 45.63049,
        "longitude": -121.95245
    },
    {
        "trail_name": "Memaloose Hills Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.2,
        "high_point(feet)": 957,
        "elevation_gain(feet)": 550,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.69458,
        "longitude": -121.34384
    },
    {
        "trail_name": "Mist Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.5,
        "high_point(feet)": 395,
        "elevation_gain(feet)": 335,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "For adventurous scramblers only",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Mitchell Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.6,
        "high_point(feet)": 1178,
        "elevation_gain(feet)": 1270,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "On sunny weekends",
        "latitude": 45.70303,
        "longitude": -121.61874
    },
    {
        "trail_name": "Mosier Plateau Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.5,
        "high_point(feet)": 620,
        "elevation_gain(feet)": 760,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.68491,
        "longitude": -121.39391
    },
    {
        "trail_name": "Mosier Twin Tunnels Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 8.5,
        "high_point(feet)": 530,
        "elevation_gain(feet)": 1000,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.64153,
        "longitude": -121.92809
    },
    {
        "trail_name": "Mount Defiance from Columbia River Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 11.6,
        "high_point(feet)": 4959,
        "elevation_gain(feet)": 4840,
        "difficulty": "Difficult",
        "seasons": "Mid-May through October",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "On weekends",
        "latitude": 45.68838,
        "longitude": -121.69039
    },
    {
        "trail_name": "Mount Defiance from Wahtum Lake Road Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.2,
        "high_point(feet)": 4959,
        "elevation_gain(feet)": 1145,
        "difficulty": "Easy",
        "seasons": "May-Nov",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.68838,
        "longitude": -121.69039
    },
    {
        "trail_name": "Mount Defiance-Starvation Ridge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 12.8,
        "high_point(feet)": 4959,
        "elevation_gain(feet)": 4970,
        "difficulty": "Difficult",
        "seasons": "Mid-May through October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "\"Yes",
        "latitude": "on weekends\"",
        "longitude": 45.68838
    },
    {
        "trail_name": "Mud Lake Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 7.4,
        "high_point(feet)": 4480,
        "elevation_gain(feet)": 1400,
        "difficulty": "Moderate",
        "seasons": "Summer into Fall",
        "family_friendly": "Yes",
        "backpackable": "es",
        "crowded": "No",
        "latitude": 44.02335,
        "longitude": -121.68222
    },
    {
        "trail_name": "Multnomah Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.4,
        "high_point(feet)": 895,
        "elevation_gain(feet)": 870,
        "difficulty": "Moderate",
        "seasons": "Year-round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Very",
        "latitude": 45.57787,
        "longitude": -122.11727
    },
    {
        "trail_name": "Multnomah Falls-Devils Rest Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 8.2,
        "high_point(feet)": 2445,
        "elevation_gain(feet)": 2595,
        "difficulty": "Difficult",
        "seasons": "\"All year",
        "family_friendly": "except when there is low-level snow\"",
        "backpackable": "No",
        "crowded": "No",
        "latitude": "Not above the lower trails",
        "longitude": 45.57787
    },
    {
        "trail_name": "Multnomah-Wahkeena Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 4.9,
        "high_point(feet)": 1560,
        "elevation_gain(feet)": 1600,
        "difficulty": "Moderate",
        "seasons": "Year round (occasional snow/ice in winter)",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.57769,
        "longitude": -122.11722
    },
    {
        "trail_name": "Munra Point from Wahclella Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6,
        "high_point(feet)": 1740,
        "elevation_gain(feet)": 2270,
        "difficulty": "\"Difficult (scramble",
        "seasons": "exposure)\"",
        "family_friendly": "\"year-round",
        "backpackable": "but hazardous when wet\"",
        "crowded": "No",
        "latitude": "No",
        "longitude": "No"
    },
    {
        "trail_name": "Munra Point from Yeon Trailhead Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6,
        "high_point(feet)": 1740,
        "elevation_gain(feet)": 2270,
        "difficulty": "\"Difficult (scramble",
        "seasons": "exposure)\"",
        "family_friendly": "\"year-round",
        "backpackable": "but hazardous when wet\"",
        "crowded": "No",
        "latitude": "No",
        "longitude": "No"
    },
    {
        "trail_name": "Nellie Corser Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 0.8,
        "high_point(feet)": 1215,
        "elevation_gain(feet)": 275,
        "difficulty": "Easy",
        "seasons": "Spring through fall",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 43.70837,
        "longitude": -121.24512
    },
    {
        "trail_name": "Nesmith Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 10.6,
        "high_point(feet)": 3872,
        "elevation_gain(feet)": 3800,
        "difficulty": "Difficult due to elevation gain",
        "seasons": "Apr-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.61242,
        "longitude": -122.00435
    },
    {
        "trail_name": "Nesmith-Oneonta Traverse Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 14.1,
        "high_point(feet)": 3872,
        "elevation_gain(feet)": 3800,
        "difficulty": "Difficult due to elevation gain and length",
        "seasons": "Apr-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.58871,
        "longitude": -122.07845
    },
    {
        "trail_name": "Nesmith-Tanner Traverse Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 16.7,
        "high_point(feet)": 3872,
        "elevation_gain(feet)": 4350,
        "difficulty": "Difficult due to elevation gain",
        "seasons": "Apr-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.61242,
        "longitude": -122.00435
    },
    {
        "trail_name": "Nick Eaton Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.2,
        "high_point(feet)": 1020,
        "elevation_gain(feet)": 970,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.68283,
        "longitude": -121.84237
    },
    {
        "trail_name": "Nick Eaton Ridge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 13.6,
        "high_point(feet)": 4095,
        "elevation_gain(feet)": 4820,
        "difficulty": "Difficult",
        "seasons": "Late spring into fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.94759,
        "longitude": -118.00471
    },
    {
        "trail_name": "North Lake Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 12.8,
        "high_point(feet)": 3988,
        "elevation_gain(feet)": 4220,
        "difficulty": "Difficult",
        "seasons": "Summer into Fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.57747,
        "longitude": -121.7927
    },
    {
        "trail_name": "Oneonta-Multnomah Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 12.3,
        "high_point(feet)": 2795,
        "elevation_gain(feet)": 3050,
        "difficulty": "Difficult",
        "seasons": "Mid-spring - fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Not in the upper reaches",
        "latitude": 45.57787,
        "longitude": -122.11727
    },
    {
        "trail_name": "Pepper Mountain Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.6,
        "high_point(feet)": 2149,
        "elevation_gain(feet)": 700,
        "difficulty": "Easy",
        "seasons": "Spring to late fall",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.45202,
        "longitude": -122.87016
    },
    {
        "trail_name": "Ponytail Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.8,
        "high_point(feet)": 350,
        "elevation_gain(feet)": 320,
        "difficulty": "Easy",
        "seasons": "Year-round except during winter storms",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.59038,
        "longitude": -122.06812
    },
    {
        "trail_name": "Pool of the Winds Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.2,
        "high_point(feet)": 1035,
        "elevation_gain(feet)": 700,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 42.89698,
        "longitude": -122.13413
    },
    {
        "trail_name": "Punchbowl Falls Park Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.1,
        "high_point(feet)": 910,
        "elevation_gain(feet)": 210,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "On summer weekends",
        "latitude": 45.42056,
        "longitude": -122.55284
    },
    {
        "trail_name": "Rainy Lake Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.2,
        "high_point(feet)": 4736,
        "elevation_gain(feet)": 755,
        "difficulty": "Easy",
        "seasons": "Summer through fall",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.57736,
        "longitude": -121.79282
    },
    {
        "trail_name": "Rainy Lake via Gorton Creek Trail Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 22,
        "high_point(feet)": 4736,
        "elevation_gain(feet)": 5430,
        "difficulty": "Difficult",
        "seasons": "Summer into fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.11099,
        "longitude": -122.02744
    },
    {
        "trail_name": "River to Rock Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.1,
        "high_point(feet)": 285,
        "elevation_gain(feet)": 270,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.38337,
        "longitude": -122.7408
    },
    {
        "trail_name": "Rock of Ages Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 10,
        "high_point(feet)": 1800,
        "elevation_gain(feet)": 3000,
        "difficulty": "\"Difficult (steepness",
        "seasons": "length",
        "family_friendly": "creek crossing",
        "backpackable": "non-maintained path)\"",
        "crowded": "Apr-Oct",
        "latitude": "No",
        "longitude": "Yes"
    },
    {
        "trail_name": "Rooster Rock Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.7,
        "high_point(feet)": 210,
        "elevation_gain(feet)": 240,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.40416,
        "longitude": -122.2975
    },
    {
        "trail_name": "Rooster Rock Wagon Road Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.8,
        "high_point(feet)": 845,
        "elevation_gain(feet)": 910,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.40416,
        "longitude": -122.2975
    },
    {
        "trail_name": "Rowena Plateau Hike",
        "trail_type": "loop",
        "distance(miles)": 2.2,
        "high_point(feet)": 710,
        "elevation_gain(feet)": 240,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.68289,
        "longitude": -121.30207
    },
    {
        "trail_name": "Ruckel Ridge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 9,
        "high_point(feet)": 3700,
        "elevation_gain(feet)": 3700,
        "difficulty": "Difficult",
        "seasons": "May-October",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 42.15842,
        "longitude": -122.90336
    },
    {
        "trail_name": "Rudolph Spur Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 10.4,
        "high_point(feet)": 3700,
        "elevation_gain(feet)": 3700,
        "difficulty": "Difficult",
        "seasons": "May-Oct",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.40777,
        "longitude": -121.78588
    },
    {
        "trail_name": "Sams Walker Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1.1,
        "high_point(feet)": 45,
        "elevation_gain(feet)": 15,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.02448,
        "longitude": -121.72791
    },
    {
        "trail_name": "Sandy River Delta Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 4.4,
        "high_point(feet)": 35,
        "elevation_gain(feet)": 40,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.54566,
        "longitude": -122.37466
    },
    {
        "trail_name": "Sevenmile Hill Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 4.8,
        "high_point(feet)": 1980,
        "elevation_gain(feet)": 1260,
        "difficulty": "Moderate",
        "seasons": "\"All year",
        "family_friendly": "but spring is best\"",
        "backpackable": "\"For older",
        "crowded": "adventurous kids\"",
        "latitude": "No",
        "longitude": "No"
    },
    {
        "trail_name": "Shady Glen Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 0.6,
        "high_point(feet)": 105,
        "elevation_gain(feet)": 55,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 42.86676,
        "longitude": -122.14558
    },
    {
        "trail_name": "She Who Watches Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.6,
        "high_point(feet)": 240,
        "elevation_gain(feet)": 45,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Group tour",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Shepperds Dell Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.2,
        "high_point(feet)": 155,
        "elevation_gain(feet)": 45,
        "difficulty": "Easy",
        "seasons": "All",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.54687,
        "longitude": -122.19751
    },
    {
        "trail_name": "Sherrard Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 0.6,
        "high_point(feet)": 4055,
        "elevation_gain(feet)": 170,
        "difficulty": "Easy",
        "seasons": "Apr-Oct",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.52919,
        "longitude": -122.08819
    },
    {
        "trail_name": "Skamania Lodge Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.3,
        "high_point(feet)": 405,
        "elevation_gain(feet)": 310,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Soda Springs Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 11.3,
        "high_point(feet)": 2105,
        "elevation_gain(feet)": 2060,
        "difficulty": "Moderate",
        "seasons": "Spring to beginning of fall",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 43.30502,
        "longitude": -122.5005
    },
    {
        "trail_name": "Sorosis Park Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1.5,
        "high_point(feet)": 745,
        "elevation_gain(feet)": 160,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.42056,
        "longitude": -122.55284
    },
    {
        "trail_name": "Spearfish Lake Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 2.2,
        "high_point(feet)": 225,
        "elevation_gain(feet)": 45,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Sometimes",
        "latitude": 44.22447,
        "longitude": -121.87185
    },
    {
        "trail_name": "St. Cloud Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1,
        "high_point(feet)": 50,
        "elevation_gain(feet)": 25,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Stacker Butte Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 5.1,
        "high_point(feet)": 3220,
        "elevation_gain(feet)": 1145,
        "difficulty": "Moderate",
        "seasons": "\"Year round",
        "family_friendly": "but spring is best\"",
        "backpackable": "O.K. for older kids",
        "crowded": "No",
        "latitude": "\"Yes",
        "longitude": "at prime bloom time on balmy spring weekends\""
    },
    {
        "trail_name": "Starvation Creek Waterfalls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.3,
        "high_point(feet)": 285,
        "elevation_gain(feet)": 145,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.68839,
        "longitude": -121.69008
    },
    {
        "trail_name": "Starvation Ridge Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 8.8,
        "high_point(feet)": 3845,
        "elevation_gain(feet)": 3855,
        "difficulty": "Difficult",
        "seasons": "May through October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.68839,
        "longitude": -121.68993
    },
    {
        "trail_name": "Strawberry Island Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 3.2,
        "high_point(feet)": 165,
        "elevation_gain(feet)": 150,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Table Mountain from Bonneville Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 15.5,
        "high_point(feet)": 3417,
        "elevation_gain(feet)": 4320,
        "difficulty": "Difficult",
        "seasons": "April-October",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.42722,
        "longitude": -121.79617
    },
    {
        "trail_name": "Table Mountain North Ridge Hike",
        "trail_type": "loop",
        "distance(miles)": 19.5,
        "high_point(feet)": 3417,
        "elevation_gain(feet)": 4350,
        "difficulty": "Difficult",
        "seasons": "April-October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "\"Yes",
        "latitude": "but not on the north loop\"",
        "longitude": 44.37032
    },
    {
        "trail_name": "Tanner Butte Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 19,
        "high_point(feet)": 4500,
        "elevation_gain(feet)": 4800,
        "difficulty": "Difficult",
        "seasons": "April-November",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.63176,
        "longitude": -121.95369
    },
    {
        "trail_name": "Tanner Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 12.2,
        "high_point(feet)": 2150,
        "elevation_gain(feet)": 1400,
        "difficulty": "Moderate",
        "seasons": "Mar-Nov",
        "family_friendly": "Too long",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.63049,
        "longitude": -121.95245
    },
    {
        "trail_name": "Tanner Creek to Eagle Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 5,
        "high_point(feet)": 605,
        "elevation_gain(feet)": 835,
        "difficulty": "Moderate",
        "seasons": "Year-round except during winter storms",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "No",
        "longitude": 45.63674
    },
    {
        "trail_name": "Tanner Cutoff Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 14.4,
        "high_point(feet)": 4500,
        "elevation_gain(feet)": 3700,
        "difficulty": "Difficult",
        "seasons": "Apr-Nov",
        "family_friendly": "\"No",
        "backpackable": "too long\"",
        "crowded": "Yes",
        "latitude": "No",
        "longitude": 45.63176
    },
    {
        "trail_name": "Tanner-Eagle Traverse Hike",
        "trail_type": "point-to-point",
        "distance(miles)": 23.6,
        "high_point(feet)": 3030,
        "elevation_gain(feet)": 4500,
        "difficulty": "Difficult",
        "seasons": "Apr-Nov",
        "family_friendly": "Too long",
        "backpackable": "Yes",
        "crowded": "only the last 7 miles near Eagle Creek",
        "latitude": 45.05683,
        "longitude": -117.32241
    },
    {
        "trail_name": "The Dalles Riverfront Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 6.6,
        "high_point(feet)": 210,
        "elevation_gain(feet)": 100,
        "difficulty": "Easy",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.38337,
        "longitude": -122.7408
    },
    {
        "trail_name": "Tomlike Mountain Hike",
        "trail_type": "loop",
        "distance(miles)": 6.8,
        "high_point(feet)": 4555,
        "elevation_gain(feet)": 1565,
        "difficulty": "Moderate",
        "seasons": "Summer into Fall",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "No",
        "latitude": "No",
        "longitude": 45.57737
    },
    {
        "trail_name": "Tooth Rock Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 1.8,
        "high_point(feet)": 440,
        "elevation_gain(feet)": 410,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 43.37293,
        "longitude": -121.06637
    },
    {
        "trail_name": "Tracy Hill Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 6.1,
        "high_point(feet)": 1840,
        "elevation_gain(feet)": 1715,
        "difficulty": "Moderate",
        "seasons": "Year round; spring is best",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.42878,
        "longitude": -121.92284
    },
    {
        "trail_name": "Triple Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.6,
        "high_point(feet)": 650,
        "elevation_gain(feet)": 680,
        "difficulty": "Moderate",
        "seasons": "Year round except during winter storms",
        "family_friendly": "Yes: but there are steep drop-offs",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.58823,
        "longitude": -122.07987
    },
    {
        "trail_name": "Two Chiefs Trail Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 15.2,
        "high_point(feet)": 1380,
        "elevation_gain(feet)": 2575,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.7253,
        "longitude": -121.73
    },
    {
        "trail_name": "Upper Hardy Creek Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 8.4,
        "high_point(feet)": 2420,
        "elevation_gain(feet)": 1875,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 44.86399,
        "longitude": -122.64219
    },
    {
        "trail_name": "Upper McCord Creek Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 1.9,
        "high_point(feet)": 540,
        "elevation_gain(feet)": 445,
        "difficulty": "Easy",
        "seasons": "Year-round except during winter storms",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.61248,
        "longitude": -122.00461
    },
    {
        "trail_name": "Viento State Park Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 5.8,
        "high_point(feet)": 325,
        "elevation_gain(feet)": 490,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.69617,
        "longitude": -121.66846
    },
    {
        "trail_name": "Wahclella Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.4,
        "high_point(feet)": 335,
        "elevation_gain(feet)": 320,
        "difficulty": "Easy",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.63151,
        "longitude": -121.95365
    },
    {
        "trail_name": "Wahkeena Falls Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.8,
        "high_point(feet)": 645,
        "elevation_gain(feet)": 565,
        "difficulty": "Moderate",
        "seasons": "All year",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "Yes",
        "latitude": 45.5774,
        "longitude": -122.11703
    },
    {
        "trail_name": "Wahtum Lake to Benson Plateau Hike",
        "trail_type": "loop",
        "distance(miles)": 13.2,
        "high_point(feet)": 4673,
        "elevation_gain(feet)": 2780,
        "difficulty": "Difficult",
        "seasons": "June into October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Around Wahtum Lake",
        "latitude": 45.645,
        "longitude": -121.91828
    },
    {
        "trail_name": "Wahtum Lake via Herman Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 22.2,
        "high_point(feet)": 4330,
        "elevation_gain(feet)": 5070,
        "difficulty": "Difficult",
        "seasons": "Summer into fall",
        "family_friendly": "For a short distance",
        "backpackable": "Yes",
        "crowded": "On summer weekends",
        "latitude": 45.68295,
        "longitude": -121.84194
    },
    {
        "trail_name": "Wahtum Lake via Pacific Crest Trail Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 33.8,
        "high_point(feet)": 4320,
        "elevation_gain(feet)": 6010,
        "difficulty": "Difficult",
        "seasons": "June into October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "Yes",
        "latitude": 44.76528,
        "longitude": -121.78714
    },
    {
        "trail_name": "Wahtum Lake via Ruckel Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 29.8,
        "high_point(feet)": 3950,
        "elevation_gain(feet)": 6270,
        "difficulty": "Difficult",
        "seasons": "May-October",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.11099,
        "longitude": -122.02744
    },
    {
        "trail_name": "Warren Lake to Mount Defiance Hike",
        "trail_type": "loop",
        "distance(miles)": 4.7,
        "high_point(feet)": 4959,
        "elevation_gain(feet)": 1340,
        "difficulty": "Moderate",
        "seasons": "Summer into fall",
        "family_friendly": "\"Yes",
        "backpackable": "for older kids\"",
        "crowded": "Yes",
        "latitude": "No",
        "longitude": 45.68838
    },
    {
        "trail_name": "Waucoma Lakes Loop Hike",
        "trail_type": "loop",
        "distance(miles)": 16.5,
        "high_point(feet)": 4737,
        "elevation_gain(feet)": 3170,
        "difficulty": "Difficult",
        "seasons": "Summer/Fall",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 44.49179,
        "longitude": -121.79491
    },
    {
        "trail_name": "Wauna Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 9.8,
        "high_point(feet)": 1688,
        "elevation_gain(feet)": 3380,
        "difficulty": "Moderate",
        "seasons": "Apr-Nov",
        "family_friendly": "No",
        "backpackable": "Yes",
        "crowded": "No",
        "latitude": 45.63982,
        "longitude": -121.9238
    },
    {
        "trail_name": "Wauna Viewpoint from Eagle Creek Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 3.4,
        "high_point(feet)": 1080,
        "elevation_gain(feet)": 1030,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.63674,
        "longitude": -121.91974
    },
    {
        "trail_name": "Wauna Viewpoint from Tooth Rock Hike",
        "trail_type": "loop",
        "distance(miles)": 5.4,
        "high_point(feet)": 1080,
        "elevation_gain(feet)": 1200,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.63982,
        "longitude": -121.9238
    },
    {
        "trail_name": "Wauneka Point Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 17.4,
        "high_point(feet)": 3872,
        "elevation_gain(feet)": 5680,
        "difficulty": "Difficult",
        "seasons": "Summer into Fall",
        "family_friendly": "No",
        "backpackable": "es",
        "crowded": "As far as Nesmith Point",
        "latitude": 45.63982,
        "longitude": -121.9238
    },
    {
        "trail_name": "Wind Mountain Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 2.9,
        "high_point(feet)": 1907,
        "elevation_gain(feet)": 1185,
        "difficulty": "Moderate",
        "seasons": "Year round",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 45.41797,
        "longitude": -122.69155
    },
    {
        "trail_name": "Wygant Peak Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 9.2,
        "high_point(feet)": 2214,
        "elevation_gain(feet)": 2365,
        "difficulty": "Moderate",
        "seasons": "all",
        "family_friendly": "No",
        "backpackable": "No",
        "crowded": "Never",
        "latitude": 45.70293,
        "longitude": -121.61879
    },
    {
        "trail_name": "Young Creek Bottomland Hike",
        "trail_type": "out-and-back",
        "distance(miles)": 4.3,
        "high_point(feet)": 45,
        "elevation_gain(feet)": 40,
        "difficulty": "Easy",
        "seasons": "Summer through falll",
        "family_friendly": "Yes",
        "backpackable": "No",
        "crowded": "No",
        "latitude": 43.74532,
        "longitude": -122.44152
    }
];